Repository guibranco/CrispyWaffle, pull requests merged in 2023-10, with the labels that each got.

#203 Add files via upload
  docs/logo.png
Labels: size/XS

#204 Update publish-docs.yml
  .github/workflows/publish-docs.yml
Labels: size/XS

#207 Update requirements.txt
  requirements.txt
Labels: size/XS

#206 Update mkdocs.yml
  mkdocs.yml
Labels: size/S

#209 Update mkdocs.yml
  mkdocs.yml
Labels: size/XS

#210 Update mkdocs.yml
  mkdocs.yml
  requirements.txt
Labels: size/XS

#212 Remove retry rule in `FtpClient.cs`
  Src/CrispyWaffle.Utils/Communications/FtpClient.cs
Labels: size/L, hacktoberfest

#218 Linter on FtpClient
  Src/CrispyWaffle.Utils/Communications/FtpClient.cs
Labels: bug, .NET, code quality

#220 Update ConversionExtensions.cs
  Src/CrispyWaffle/Extensions/ConversionExtensions.cs
Labels: code quality, size/S

#235 Update installation.md
  appveyor.yml
  docs/changelog.md
  docs/installation.md
  docs/user-guide/basic-usage.md
  docs/user-guide/caching.md
  docs/user-guide/events.md
  docs/user-guide/logging.md
  docs/user-guide/messaging.md
  docs/user-guide/scheduled-jobs.md
  docs/user-guide/service-locator.md
Labels: size/M
