Repository guibranco/CrispyWaffle, pull requests merged in 2024-09, with the labels that each got.

#529 Improve documentation clarity for command handling
  docs/user-guide/commands.md
Labels: documentation, size/S, ☑️ auto-merge, Review effort [1-5]: 2

#532 Remove CODE_OF_CONDUCT.md file
  CODE_OF_CONDUCT.md
Labels: documentation, size/L, ☑️ auto-merge, Review effort [1-5]: 1

#533 Remove SECURITY.md file and its contents
  SECURITY.md
Labels: documentation, size/S, ☑️ auto-merge, Review effort [1-5]: 1, Possible security concern

#540 Enhance TestObjects class by sealing it
  Tests/CrispyWaffle.Tests/Commands/TestObjects.cs
Labels: enhancement, size/XS, Review effort [1-5]: 1

#542 Improve documentation in RedisExtensions.cs
  Src/CrispyWaffle.Redis/Utils/RedisExtensions.cs
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 1

#544 Add CouchDB support and related tests
  CrispyWaffle.sln
  Directory.Packages.props
  Src/CrispyWaffle.CouchDB/CouchDBCacheRepository.cs
  Src/CrispyWaffle.CouchDB/CrispyWaffle.CouchDB.csproj
  Src/CrispyWaffle.CouchDB/DTOs/CouchDoc.cs
  Src/CrispyWaffle/Cache/ICacheRepository.cs
  Src/CrispyWaffle/Log/Adapters/RollingTextFileLogAdapter.cs
  Tests/CrispyWaffle.Tests/Cache/CouchDBCacheRepositoryTests.cs
  Tests/CrispyWaffle.Tests/CrispyWaffle.Tests.csproj
  appveyor.yml
Labels: documentation, enhancement, help wanted, good first issue, tests, cache, dependencies, database, .NET, communications, packages, hacktoberfest, size/XL, 🚦 awaiting triage, CouchDB, Review effort [1-5]: 4

#548 Refactor tests to use async/await instead of Thread.Sleep
  Tests/CrispyWaffle.Tests/Cache/CouchDBCacheRepositoryTests.cs
  Tests/CrispyWaffle.Tests/Composition/ServiceLocatorTests.cs
  Tests/CrispyWaffle.Tests/Scheduler/JobManagerTests.cs
  Tests/CrispyWaffle.Tests/Scheduler/JobRunnerTests.cs
Labels: enhancement, size/M, 🚦 awaiting triage, Review effort [1-5]: 2

#552 Enhance CI workflows with Docker Compose integration
  .github/workflows/deep-source.yml
  .github/workflows/sonarcloud.yml
  CrispyWaffle.sln
  Src/CrispyWaffle.CouchDB/Cache/CouchDBCacheDocument.cs
  Src/CrispyWaffle.CouchDB/Cache/CouchDBCacheRepository.cs
  Src/CrispyWaffle.CouchDB/Utils/Communications/CouchDBConnector.cs
  Src/CrispyWaffle.Redis/Cache/RedisCacheRepository.cs
  Tests/CrispyWaffle.IntegrationTests/Cache/CouchDBCacheRepositoryTests.cs
  Tests/CrispyWaffle.IntegrationTests/CrispyWaffle.IntegrationTests.csproj
  Tests/CrispyWaffle.Tests/Cache/CouchDBCacheRepositoryTests.cs
  Tests/CrispyWaffle.Tests/Log/Adapters/RollingTextFileLogAdapterTests.cs
  appveyor.yml
  docker-compose.yml
Labels: enhancement, size/XL, Review effort [1-5]: 4

#554 Update version to 8.2 and enhance changelog
  Src/CrispyWaffle.CouchDB/Cache/CouchDBCacheRepository.cs
  Tests/CrispyWaffle.IntegrationTests/Cache/CouchDBCacheRepositoryTests.cs
  Tests/CrispyWaffle.Tests/Cache/CouchDBCacheRepositoryTests.cs
  Tests/CrispyWaffle.Tests/Log/Adapters/RollingTextFileLogAdapterTests.cs
  appveyor.yml
  docs/changelog.md
Labels: documentation, enhancement, size/L, ☑️ auto-merge, Review effort [1-5]: 2

#556 Remove pull request template file from GitHub repository
  .github/pull_request_template.md
Labels: documentation, size/S, ☑️ auto-merge, Review effort [1-5]: 1

#557 Simplify Infisical secrets check workflow
  .github/workflows/infisical-secrets-check.yml
Labels: enhancement, size/M, ☑️ auto-merge, Review effort [1-5]: 2
