Repository guibranco/CrispyWaffle, pull requests merged in 2024-06, with the labels that each got.

#407 Update Directory.Build.props
  Directory.Build.props
Labels: size/XS

#410 Update appveyor.yml
  appveyor.yml
Labels: size/XS

#411 Update appveyor.yml
  Directory.Packages.props
  Tests/CrispyWaffle.I18n.PtBr.Tests/CrispyWaffle.I18n.PtBr.Tests.csproj
  Tests/CrispyWaffle.Tests/CrispyWaffle.Tests.csproj
  appveyor.yml
Labels: size/S

#412 Update appveyor.yml
  appveyor.yml
Labels: size/XS

#416 Add the commands feature
  Src/CrispyWaffle/Commands/CommandsConsumer.cs
  Src/CrispyWaffle/Commands/ICommand.cs
  Src/CrispyWaffle/Commands/ICommandHandler.cs
  Src/CrispyWaffle/Commands/ICommandHandlerAsync.cs
  Tests/CrispyWaffle.Tests/Commands/CommandsTests.cs
  Tests/CrispyWaffle.Tests/Commands/TestObjects.cs
  docs/user-guide/commands.md
Labels: size/L

#425 Update readme
  README.md
  docs/contributing.md
Labels: size/L

#428 Fix readme files
  README.md
  docs/contributing.md
Labels: size/S
