Repository guibranco/CrispyWaffle, pull requests merged in 2024-01, with the labels that each got.

#278 Create codacy.yml
  .github/workflows/codacy.yml
Labels: size/M

#279 Delete .github/workflows/qodana.yml
  .github/workflows/qodana.yml
Labels: size/S

#286 Replaced MD5CryptoServiceProvider to MD5.Create
  Src/CrispyWaffle/Cryptography/Security.cs
Labels: size/XS

#294 Create SECURITY.md
  SECURITY.md
Labels: size/S

#293 Update mkdocs.yml
  mkdocs.yml
Labels: size/XS

#298 Update README.md
  README.md
Labels: size/L

#295 Create bug-fix-or-feature.md
  .github/PULL_REQUEST_TEMPLATE/bug-fix-or-feature.md
Labels: size/S

#301 Update appveyor.yml
  appveyor.yml
Labels: size/XS

#296 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: size/L

#297 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/S

#305 Fix some code smells
  .config/dotnet-tools.json
  .vscode/launch.json
  .vscode/tasks.json
  Src/CrispyWaffle.Configuration/packages.lock.json
  Src/CrispyWaffle.ElasticSearch/packages.lock.json
  Src/CrispyWaffle.Elmah/packages.lock.json
  Src/CrispyWaffle.Log4Net/packages.lock.json
  Src/CrispyWaffle.RabbitMQ/packages.lock.json
  Src/CrispyWaffle.Redis/packages.lock.json
  Src/CrispyWaffle.Utils/packages.lock.json
  Src/CrispyWaffle/Composition/ServiceLocator.cs
  Src/CrispyWaffle/Composition/TooManyImplementationsException.cs
  Src/CrispyWaffle/Cryptography/Security.cs
  Src/CrispyWaffle/Events/IEventHandlerAsync.cs
  Src/CrispyWaffle/Extensions/ConversionExtensions.cs
  Src/CrispyWaffle/GoodPractices/InvalidTelephoneNumberException.cs
  Src/CrispyWaffle/Infrastructure/EnvironmentHelper.cs
  Src/CrispyWaffle/Log/Handlers/DefaultExceptionHandler.cs
  Src/CrispyWaffle/Serialization/Adapters/BaseSerializerAdapter.cs
  Src/CrispyWaffle/Utilities/QueryStringBuilder.cs
  Src/CrispyWaffle/packages.lock.json
  Tests/CrispyWaffle.Tests/Extensions/ConversionExtensionsTests.cs
  Tests/CrispyWaffle.Tests/packages.lock.json
Labels: size/XXL

#310 Update SECURITY.md
  SECURITY.md
Labels: size/XS

#311 Update and rename .github/PULL_REQUEST_TEMPLATE/bug-fix-or-feature.md…
  .github/PULL_REQUEST_TEMPLATE/bug-fix-or-feature.md
  .github/pull_request_template.md
Labels: size/M

#314 Update pull_request_template.md
  .github/pull_request_template.md
Labels: size/XS

#319 Create contributing.md
  docs/contributing.md
Labels: size/S
