Repository guibranco/CrispyWaffle, pull requests merged in 2024-07, with the labels that each got.

#433 Use centralized package manager
  Directory.Packages.props
  Tests/CrispyWaffle.I18n.PtBr.Tests/CrispyWaffle.I18n.PtBr.Tests.csproj
  Tests/CrispyWaffle.Tests/CrispyWaffle.Tests.csproj
Labels: enhancement, dependencies, size/M, code quality, nuget, ☑️ auto-merge

#434 Create infisical-secrets-check.yml
  .github/workflows/infisical-secrets-check.yml
Labels: size/M, ☑️ auto-merge

#442 Update sonar-cloud.yml
  .github/workflows/sonar-cloud.yml
Labels: size/XS, ☑️ auto-merge

#443 Add Pixee SonarCloud
  .github/workflows/sonarcloud-pixeebot.yml
  .github/workflows/sonarcloud.yml
Labels: size/M, ☑️ auto-merge

#445 Fix warnings
  .deepsource.toml
  .sonarlint/CrispyWaffle.json
  CrispyWaffle.sln
  CrispyWaffle.sln.DotSettings
  Directory.Build.props
  Src/CrispyWaffle.Configuration/Connection.cs
  Src/CrispyWaffle.Configuration/ConnectionNameAttribute.cs
  Src/CrispyWaffle.Configuration/Credentials.cs
  Src/CrispyWaffle.Elmah/ElmahExceptionHandler.cs
  Src/CrispyWaffle.Log4Net/Log4NetLogProvider.cs
  Src/CrispyWaffle/Attributes/QueryStringBuilderIgnoreAttribute.cs
  Src/CrispyWaffle/Attributes/QueryStringBuilderKeyNameAttribute.cs
  Src/CrispyWaffle/Composition/IBootstrapper.cs
  Src/CrispyWaffle/Composition/IDependencyResolver.cs
  Src/CrispyWaffle/Composition/Lifetime.cs
  Src/CrispyWaffle/Composition/ServiceLocator.cs
  Src/CrispyWaffle/Extensions/StringExtensions.cs
  Src/CrispyWaffle/Utilities/IUpdateable.cs
  Src/CrispyWaffle/Utilities/LazyResettable.cs
  Tests/CrispyWaffle.Tests/Fixtures/ConfigurationFixture.cs
  Tests/CrispyWaffle.Tests/Fixtures/LoggingFixture.cs
  Tests/CrispyWaffle.Tests/Infrastructure/EnvironmentHelperTests.cs
  appveyor.yml
Labels: size/XL, ☑️ auto-merge

#446 Feature/fix warnings
  Src/CrispyWaffle.Configuration/Credentials.cs
  Tests/CrispyWaffle.Tests/Cryptography/SecurityTests.cs
  Tests/CrispyWaffle.Tests/Extensions/ConversionExtensionsTests.cs
  Tests/CrispyWaffle.Tests/Serialization/JsonSerializerAdapterTests.cs
  Tests/CrispyWaffle.Tests/Serialization/NewtonsoftJsonSerializerAdapterTests.cs
  Tests/CrispyWaffle.Tests/Utilities/LazyResettableTests.cs
  Tests/CrispyWaffle.Tests/Validations/PersonalDataValidationTests.cs
  appveyor.yml
Labels: size/M, ☑️ auto-merge

#447 Update contributors-readme.yml
  .github/workflows/contributors-readme.yml
Labels: size/XS, ☑️ auto-merge

#450 Fix contributing section of readme files
  .github/workflows/contributors-readme.yml
  README.md
  docs/contributing.md
Labels: bug, github-actions, ☑️ auto-merge

#454 Fix GH Action
  .github/workflows/contributors-readme.yml
  README.md
  docs/contributing.md
Labels: bug, size/L, github-actions, ☑️ auto-merge

#458 Update changelog.md
  docs/changelog.md
Labels: size/XS, ☑️ auto-merge

#463 Remove binary serializer
  README.md
  Src/CrispyWaffle/Serialization/Adapters/BinarySerializerAdapter.cs
  Src/CrispyWaffle/Serialization/SerializerConverter.cs
  Src/CrispyWaffle/Serialization/SerializerFactory.cs
  Src/CrispyWaffle/Serialization/SerializerFormat.cs
  docs/contributing.md
  docs/user-guide/basic-usage.md
Labels: documentation, enhancement, help wanted, good first issue, 🛠 WIP, dependencies, .NET, security, size/L, Serializers, hacktoberfest, 🚦awaiting triage

#464 Update infisical-secrets-check.yml
  .github/workflows/infisical-secrets-check.yml
  Src/CrispyWaffle/Serialization/SerializerConverter.cs
Labels: size/S, ☑️ auto-merge

#467 Update appveyor.yml
  appveyor.yml
Labels: size/S, ☑️ auto-merge

#470 Upgrade elastic search dependencies
  Directory.Packages.props
  README.md
  Src/CrispyWaffle.ElasticSearch/CrispyWaffle.ElasticSearch.csproj
  Src/CrispyWaffle.ElasticSearch/Helpers/Extensions.cs
  Src/CrispyWaffle.ElasticSearch/Log/ElasticSearchLogProvider.cs
  Src/CrispyWaffle.ElasticSearch/Utils/Communications/ElasticConnector.cs
  Src/CrispyWaffle.ElasticSearch/Utils/Communications/ElasticWrapper.cs
  docs/contributing.md
Labels: documentation, enhancement, help wanted, good first issue, 🛠 WIP, dependencies, .NET, size/L, nuget, packages, hacktoberfest, 🚦awaiting triage, ElasticSearch

#473 Release v8.0
  appveyor.yml
  docs/changelog.md
Labels: size/XS, ☑️ auto-merge
