Repository guibranco/CrispyWaffle, pull requests merged in 2024-08, with the labels that each got.

#479 Implement rolling text file log adapter
  README.md
  Src/CrispyWaffle/Log/Adapters/ICategorizedLogAdapter.cs
  Src/CrispyWaffle/Log/Adapters/ILogAdapter.cs
  Src/CrispyWaffle/Log/Adapters/ITextFileLogAdapter.cs
  Src/CrispyWaffle/Log/Adapters/RollingTextFileLogAdapter.cs
  Src/CrispyWaffle/Log/LogLevel.cs
  Src/CrispyWaffle/Log/Providers/ILogProvider.cs
  Src/CrispyWaffle/Log/Providers/TextFileLogProvider.cs
  Tests/CrispyWaffle.Tests/Serialization/RollingTextFileLogAdapterTests.cs
  docs/contributing.md
Labels: enhancement, help wanted, good first issue, 🛠 WIP, log, .NET, hacktoberfest, size/XL, gitauto

#484 Rename Tests/CrispyWaffle.Tests/Serialization/RollingTextFileLogAdapt…
  Src/CrispyWaffle/Log/Adapters/ILogAdapter.cs
  Src/CrispyWaffle/Log/Adapters/RollingTextFileLogAdapter.cs
  Src/CrispyWaffle/Log/Providers/TextFileLogProvider.cs
  Tests/CrispyWaffle.Tests/Log/Adapters/RollingTextFileLogAdapterTests.cs
Labels: size/L, ☑️ auto-merge

#485 Fix build
  CrispyWaffle.sln
  Directory.Packages.props
  Src/CrispyWaffle.Eventlog/Log/Adapters/EventLogAdapter.cs
  Src/CrispyWaffle.Eventlog/Log/Providers/EventIdProvider.cs
  Src/CrispyWaffle.Eventlog/Log/Providers/EventLogProvider.cs
  Src/CrispyWaffle.Eventlog/Log/Providers/IEventIdProvider.cs
  Src/CrispyWaffle.Utils/Communications/FtpClient.cs
  Src/CrispyWaffle/Log/Adapters/RollingTextFileLogAdapter.cs
  Src/CrispyWaffle/Log/LogConsumer.cs
  Src/CrispyWaffle/TemplateRendering/Engines/MustacheTemplateRender.cs
  appveyor.yml
Labels: size/L, ☑️ auto-merge

#486 Update SECURITY.md
  SECURITY.md
Labels: size/XS, ☑️ auto-merge

#487 Add rolling text file log adapter documentation
  README.md
  Src/CrispyWaffle/Log/Adapters/RollingTextFileLogAdapter.cs
  Tests/CrispyWaffle.Tests/Log/Adapters/RollingTextFileLogAdapterTests.cs
  docs/contributing.md
  docs/user-guide/logging.md
Labels: documentation, enhancement, help wanted, good first issue, log, size/L, hacktoberfest, 🚦awaiting triage

#495 Fix location
  CrispyWaffle.sln
  Src/CrispyWaffle.EventLog/CrispyWaffle.EventLog.csproj
  Src/CrispyWaffle.EventLog/Log/Adapters/EventLogAdapter.cs
  Src/CrispyWaffle.EventLog/Log/Providers/EventIdProvider.cs
  Src/CrispyWaffle.EventLog/Log/Providers/EventLogProvider.cs
  Src/CrispyWaffle.EventLog/Log/Providers/IEventIdProvider.cs
Labels: size/XS, ☑️ auto-merge

#498 Fix code smells
  Src/CrispyWaffle.Configuration/Credentials.cs
  Src/CrispyWaffle.Configuration/IConnection.cs
  Src/CrispyWaffle.Configuration/IConnectionCredential.cs
  Src/CrispyWaffle.Configuration/ISecureCredentialProvider.cs
  Src/CrispyWaffle.Configuration/SecureCredentialProvider.cs
  Src/CrispyWaffle.Elmah/ElmahExceptionHandler.cs
  Src/CrispyWaffle.Log4Net/Log4NetLogProvider.cs
  Src/CrispyWaffle.RabbitMQ/Helpers/IQueuing.cs
  Src/CrispyWaffle.RabbitMQ/Helpers/QueueNameAttribute.cs
  Src/CrispyWaffle.RabbitMQ/Utils/Communications/RabbitMQConnector.cs
Labels: size/M, ☑️ auto-merge

#500 Guibranco patch 1
  appveyor.yml
Labels: size/S, ☑️ auto-merge

#507 Update README.md
  README.md
  docs/images/supported-versions-2024-08.png
Labels: size/L, ☑️ auto-merge

#528 Enhance AppVeyor configuration with SONAR_TOKEN
  appveyor.yml
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 2
